name: AnchoredPortals
version: 0.0.0.33
description: Plugin to "anchor" a given portal to another portal.
author: Feaelin (Iain E. Davis) <iain@ruhlendavis.org>
website: http://dev.bukkit.org/bukkit-plugins/anchoredportals/

main: org.ruhlendavis.mc.anchoredportals.AnchoredPortals
