name: AnchoredPortals
version: 1.0.2.44
description: Plugin to "anchor" a given portal to another portal.
author: Feaelin (Iain E. Davis) <iain@ruhlendavis.org>
website: http://dev.bukkit.org/bukkit-plugins/anchoredportals/

main: org.anchoredportals.main.AnchoredPortals
